# Generated by Django 4.2.20 on 2025-04-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_credential_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
