# Generated by Django 4.2.20 on 2025-04-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_credential_url_alter_credential_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
