# Generated by Django 4.2.20 on 2025-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='user',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
